// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnnrpxosrhjusbqxigog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpubnJweG9zcmhqdXNicXhpZ29nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyNjc3MjQsImV4cCI6MjA1NDg0MzcyNH0.N01ZyfA9Fht45NOB9Z3QLalnGAnMU8TB3ZWru0ivh6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);